[project]
name = "quron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jace Trent", email = "jacetrent77@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.31.0",
    "httpx2>=2.13.1",
    "pydantic-settings>=2.15.0",
    "sqlmodel>=0.0.47",
    "structlog>=26.1.0",
]

[project.scripts]
quron = "quron:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint]
preview = true

[tool.ruff.lint.per-file-ignores]
"src/schemas/**" = ['mixed-case-variable-in-class-scope']
"src/data/__init__.py" = ["non-empty-init-module"]
"src/quron/__init__.py" = ["non-empty-init-module"]
